/* VENDORED. Do not edit this file to change behaviour.
 *
 * Source:    novara-matching/console/matchcore.js
 * Repo:      github.com/jackyminkler/novara-matching
 * Copied:    2026-08-27, verbatim. Only this header was added.
 * sha256:    482b94682266418f3b4b2b569219d4cc7790febcabe20374956962fe70a82108
 *            (of the source file at copy time; `shasum -a 256` it to compare)
 *
 * DRIFT RULE (MATCHING.md section 12). Three copies of rank now exist:
 * novara-matching/formats/rank.py (canonical), novara-matching/console/
 * matchcore.js (the Match Console), and this one. A behaviour change must land
 * in all three together, or be logged as a divergence. Any edit here, including
 * one that looks cosmetic, gets a dated block in MATCHING_INBOX.md in the same
 * commit. Fixes belong in rank.py first; this file follows.
 *
 * The typed wrapper, the serializer, and everything the app actually calls live
 * in ./index.ts. Nothing else in the app imports this file directly.
 */
/* Novara matchcore — rank mode, ported line-for-line from
 * novara-matching/formats/rank.py @ v1.3.0 (continuous pace, lower-bound
 * ranking, parse-rate guard). RULE (MATCHING.md §12): any behaviour change
 * must land in BOTH files or be logged as a divergence in the decision log.
 * Verified against the Python implementation by tests/parity (node). */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.matchcore = factory();
}(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  // ── App pace buckets, mirrored from novara core.js PACE_BUCKETS ─────────
  const PACE_BUCKETS = [[6, 7], [7, 8], [8, 9], [9, 10], [10, 11], [11, 13]];
  const DEFAULT_LAMBDA = 0.5;
  // Curve and gate are two numbers — mirrors formats/rank.py exactly.
  // See the long-form rationale there; the short version is that a single
  // linear tolerance tied every pair beyond 90s at zero AND doubled as the
  // exclusion threshold, so ranking could not change without changing who is
  // excluded.
  const PACE_HALF_LIFE_SEC = 60;
  const PACE_GATE_SEC = 90;

  const DEFAULT_COLUMNS = {
    name:        ["name"],
    email:       ["email"],
    pace_min:    ["pace min", "fastest pace", "pace_min"],
    pace_max:    ["pace max", "slowest pace", "pace_max"],
    pace_bands:  ["pace you can comfortably", "pace band", "pace_bands"],
    availability: ["available", "availability", "days free", "when can you"],
    run_types:   ["run type", "kind of runs", "run_types"],
    neighborhood: ["neighborhood", "neighbourhood", "area", "location"],
    share:       ["topics do you have experience", "can share", "topics_share"],
    learn:       ["topics would you like to learn", "want to learn", "topics_learn"],
  };

  const DEFAULT_WEIGHTS = {
    pace: 0.35, availability: 0.25, runType: 0.15,
    neighborhood: 0.10, topic: 0.15,
  };

  const BAND_WORDS = {   // multi-select band labels, event-form style
    "faster than 8": [0, 1], "sub-8": [0, 1], "7 to 8": [1], "8 to 9": [2],
    "9 to 10": [3], "10 to 11": [4], "11 to 12": [5], "12+": [5], "11+": [5],
  };

  function norm(s) {
    if (s === null || s === undefined) return "";
    return String(s).normalize("NFC").replace(/\s+/g, " ").trim();
  }

  function tokens(cell) {
    const c = norm(cell);
    if (!c) return [];
    return c.split(/[,;/]+/).map(t => t.trim().toLowerCase()).filter(Boolean);
  }

  function paceToMin(v) {
    v = norm(v);
    if (!v) return null;
    let m = v.match(/^(\d{1,2}):(\d{2})$/);
    if (m) return parseInt(m[1], 10) + parseInt(m[2], 10) / 60.0;
    m = v.match(/^(\d+(?:\.\d+)?)\s*(s|sec|seconds)?/);
    if (!m) return null;
    const x = parseFloat(m[1]);
    if (m[2]) return x / 60.0;          // explicit seconds
    return x > 30 ? x / 60.0 : x;       // bare number > 30 means seconds/mile
  }

  function bucketsFor(lo, hi) {
    const l = Math.min(lo, hi), h = Math.max(lo, hi);
    const out = [];
    for (let i = 0; i < PACE_BUCKETS.length; i++) {
      const bmin = PACE_BUCKETS[i][0], bmax = PACE_BUCKETS[i][1];
      let ok;
      if (l === h) ok = l >= bmin && (i === PACE_BUCKETS.length - 1 ? l <= bmax : l < bmax);
      else ok = l < bmax && h > bmin;
      if (ok) out.push(i);
    }
    if (!out.length) return h <= PACE_BUCKETS[0][0] ? [0] : [PACE_BUCKETS.length - 1];
    return out;
  }

  function resolveCols(header, columns) {
    const low = new Map();
    for (const h of header) if (h) low.set(h.toLowerCase(), h);
    const out = {};
    for (const key of Object.keys(columns)) {
      for (const frag of columns[key]) {
        let hit = null;
        for (const [lh, h] of low) if (lh.includes(frag.toLowerCase())) { hit = h; break; }
        if (hit) { out[key] = hit; break; }
      }
    }
    return out;
  }

  // rows: array of objects (header -> cell), e.g. from parseCSV
  function loadRows(rows, columns) {
    const spec = {};
    for (const k of Object.keys(DEFAULT_COLUMNS)) spec[k] = DEFAULT_COLUMNS[k].slice();
    for (const k of Object.keys(columns || {})) {
      const v = columns[k];
      spec[k] = typeof v === "string" ? [v] : v.slice();
    }
    if (!rows.length) return { people: [], cols: {} };
    const cols = resolveCols(Object.keys(rows[0]), spec);

    const people = [];
    rows.forEach((r, i) => {
      const g = k => (k in cols ? norm(r[cols[k]]) : "");
      let buckets = [], paceLo = null, paceHi = null;
      let lo = paceToMin(g("pace_min")), hi = paceToMin(g("pace_max"));
      if (lo !== null || hi !== null) {
        lo = lo !== null ? lo : hi;
        hi = hi !== null ? hi : lo;
        paceLo = Math.min(lo, hi); paceHi = Math.max(lo, hi);
        buckets = bucketsFor(lo, hi);
      } else if (g("pace_bands")) {
        const got = new Set();
        const cell = g("pace_bands").toLowerCase();
        for (const w of Object.keys(BAND_WORDS))
          if (cell.includes(w)) BAND_WORDS[w].forEach(b => got.add(b));
        buckets = [...got].sort((a, b) => a - b);
      }
      const name = g("name") || `row ${i + 2}`;
      people.push({
        id: g("email").toLowerCase() || name.toLowerCase(),
        name, email: g("email"),
        buckets, pace_lo: paceLo, pace_hi: paceHi,
        avail: new Set(tokens(g("availability"))),
        run_types: new Set(tokens(g("run_types"))),
        hood: g("neighborhood").toLowerCase(),
        share: new Set(tokens(g("share"))),
        learn: new Set(tokens(g("learn"))),
      });
    });

    // Parse-rate guard (trap 10)
    if ("pace_min" in cols) {
      const raw = rows.map(r => norm(r[cols.pace_min])).filter(Boolean);
      if (raw.length) {
        const ok = raw.filter(v => paceToMin(v) !== null).length;
        if (ok / raw.length < 0.7)
          throw new Error(
            `pace column '${cols.pace_min}' parsed ${ok}/${raw.length} values; ` +
            "check the format (mm:ss or minutes per mile) instead of scoring blanks");
      }
    }
    return { people, cols };
  }

  // ── set helpers ─────────────────────────────────────────────────────────
  const inter = (a, b) => new Set([...a].filter(x => b.has(x)));
  const union = (a, b) => new Set([...a, ...b]);

  // ── dimension scorers: each returns [score, hasData, why|null] ──────────
  function dPace(a, b, halfLifeSec, gateSec) {
    const hl = halfLifeSec === undefined ? PACE_HALF_LIFE_SEC : halfLifeSec;
    const gate = gateSec === undefined ? PACE_GATE_SEC : gateSec;
    if (a.pace_lo !== null && a.pace_lo !== undefined &&
        b.pace_lo !== null && b.pace_lo !== undefined) {
      const gapMin = Math.max(a.pace_lo, b.pace_lo) - Math.min(a.pace_hi, b.pace_hi);
      const gapSec = Math.max(0.0, gapMin * 60.0);
      const s = Math.pow(0.5, gapSec / hl);
      let why = null;
      if (gapSec === 0) why = "pace ranges overlap";
      else if (gapSec <= gate) why = `paces within ${Math.round(gapSec)}s/mile`;
      return [s, true, why];
    }
    if (!a.buckets.length || !b.buckets.length) return [0.0, false, null];
    let d = Infinity;
    for (const x of a.buckets) for (const y of b.buckets) d = Math.min(d, Math.abs(x - y));
    const s = Math.pow(0.5, d);
    const why = d === 0 ? "same pace band" : d === 1 ? "adjacent pace band" : null;
    return [s, true, why];
  }

  function dAvail(a, b) {
    if (!a.avail.size || !b.avail.size) return [0.0, false, null];
    const shared = inter(a.avail, b.avail);
    const s = shared.size / Math.max(1, Math.min(a.avail.size, b.avail.size));
    const why = shared.size ? "both free " + [...shared].sort().slice(0, 2).join(", ") : null;
    return [s, true, why];
  }

  function dRuntype(a, b) {
    if (!a.run_types.size || !b.run_types.size) return [0.0, false, null];
    const shared = inter(a.run_types, b.run_types);
    const u = union(a.run_types, b.run_types);
    const why = shared.size ? "both like " + [...shared].sort().slice(0, 2).join(", ") : null;
    return [shared.size / u.size, true, why];
  }

  function titleCase(s) { return s.replace(/\b\w/g, c => c.toUpperCase()); }

  function dHood(a, b) {
    if (!a.hood || !b.hood) return [0.0, false, null];
    const same = a.hood === b.hood;
    return [same ? 1.0 : 0.0, true, same ? `both in ${titleCase(a.hood)}` : null];
  }

  function dTopic(a, b) {
    if (!(a.learn.size || a.share.size) || !(b.learn.size || b.share.size))
      return [0.0, false, null];
    const fab = a.learn.size ? inter(a.learn, b.share).size / Math.max(1, a.learn.size) : 0.0;
    const fba = b.learn.size ? inter(b.learn, a.share).size / Math.max(1, b.learn.size) : 0.0;
    let s = (fab + fba) / 2;
    if (fab > 0.3 && fba > 0.3) s = Math.min(1.0, s + 0.2);
    const hits = [...inter(a.learn, b.share)].sort();
    const why = hits.length ? "can talk " + hits.slice(0, 2).join(", ") : null;
    return [s, true, why];
  }

  const DIMS = [["pace", dPace], ["availability", dAvail], ["runType", dRuntype],
                ["neighborhood", dHood], ["topic", dTopic]];

  const round4 = x => Math.round((x + Number.EPSILON) * 1e4) / 1e4;

  function scorePair(a, b, weights, tolSec) {
    weights = weights || DEFAULT_WEIGHTS;
    let totalW = 0;
    for (const [k] of DIMS) totalW += weights[k] || 0;
    let got = 0.0, activeW = 0.0;
    const whys = [], breakdown = {};
    for (const [key, fn] of DIMS) {
      const w = weights[key] || 0;
      if (w <= 0) continue;
      const [s, has, why] = key === "pace" ? fn(a, b, tolSec) : fn(a, b);
      breakdown[key] = has ? s : null;
      if (has) {
        got += w * s;
        activeW += w;
        if (why) whys.push(why);
      }
    }
    const total = activeW ? got / activeW : 0.0;
    const confidence = totalW ? activeW / totalW : 0.0;
    return { total: round4(total), confidence: round4(confidence),
             breakdown, why: whys.slice(0, 3).join("; ") };
  }

  function rank(people, opts) {
    opts = opts || {};
    const weights = opts.weights || DEFAULT_WEIGHTS;
    const topN = opts.top_n === undefined ? 3 : opts.top_n;
    const lam = opts.lambda === undefined ? DEFAULT_LAMBDA : opts.lambda;
    const tolSec = opts.paceToleranceSec;
    const out = {};
    for (const a of people) {
      const cands = [];
      for (const b of people) {
        if (b.id === a.id) continue;
        const r = scorePair(a, b, weights, tolSec);
        if (!r.why) continue;           // unexplainable matches are not surfaced
        r.lb = round4(r.total - lam * (1 - r.confidence));
        r.name = b.name; r.email = b.email;
        cands.push(r);
      }
      cands.sort((x, y) => (y.lb - x.lb) || (y.total - x.total) ||
        (x.name.toLowerCase() < y.name.toLowerCase() ? -1 :
         x.name.toLowerCase() > y.name.toLowerCase() ? 1 : 0));
      out[a.id] = { name: a.name, email: a.email, matches: cands.slice(0, topN) };
    }
    return out;
  }

  // ── CSV (RFC 4180-ish: quotes, embedded newlines, CRLF, BOM) ────────────
  function parseCSV(text) {
    if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
    const grid = [];
    let row = [], field = "", inQ = false;
    for (let i = 0; i < text.length; i++) {
      const c = text[i];
      if (inQ) {
        if (c === '"') {
          if (text[i + 1] === '"') { field += '"'; i++; }
          else inQ = false;
        } else field += c;
      } else if (c === '"') inQ = true;
      else if (c === ",") { row.push(field); field = ""; }
      else if (c === "\n" || c === "\r") {
        if (c === "\r" && text[i + 1] === "\n") i++;
        row.push(field); field = "";
        grid.push(row); row = [];
      } else field += c;
    }
    if (field !== "" || row.length) { row.push(field); grid.push(row); }
    while (grid.length && grid[grid.length - 1].every(c => c === "")) grid.pop();
    if (!grid.length) return [];
    const header = grid[0];
    return grid.slice(1).map(r => {
      const o = {};
      header.forEach((h, j) => {
        if (h) o[h] = r[j] !== undefined ? r[j] : "";  // overflow cells under null: dropped
      });
      return o;
    });
  }

  function toCSV(res) {
    const esc = v => {
      v = String(v === undefined || v === null ? "" : v);
      return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
    };
    const lines = [["name", "email", "match", "match_email",
                    "score", "confidence", "lower_bound", "why"].join(",")];
    for (const id of Object.keys(res)) {
      const row = res[id];
      for (const m of row.matches)
        lines.push([row.name, row.email, m.name, m.email,
                    m.total, m.confidence, m.lb, m.why].map(esc).join(","));
    }
    return lines.join("\n");
  }

  return { PACE_BUCKETS, DEFAULT_LAMBDA, PACE_HALF_LIFE_SEC, PACE_GATE_SEC, DEFAULT_COLUMNS,
           DEFAULT_WEIGHTS, BAND_WORDS, norm, tokens, paceToMin, bucketsFor,
           resolveCols, loadRows, scorePair, rank, parseCSV, toCSV };
}));
